substitutions:
  name: "hanp1"
  friendly_name: "HanP1, Electric meter for P1/HAN port"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  min_version: 2025.2.0
  project:
    name: "HanP1.electrical meter"
    version: "1.1.0"

esp8266:
  board: esp07s

external_components:
  - source: github://Tozzi89/HanP1@main
    components: [ p1reader ]

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "HANP1"

captive_portal:

# Enable logging
logger:
  level: INFO
  baud_rate: 0 # disable logging over uart
  esp8266_store_log_strings_in_flash: false # Avoid flash wear and tear
  
# Enable Home Assistant API
api:

ota:
  platform: esphome

uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 115200
  rx_buffer_size: 3072    # UART Buffer size controls polling frequency

status_led:
  pin: 12

output:
  - platform: gpio
    pin: 13
    id: 'green'

  - platform: gpio
    pin: 14
    id: 'blue'

switch:
  - platform: output
    name: "Green"
    output: 'green'
    restore_mode: ALWAYS_ON

  - platform: output
    name: "Blue"
    output: 'blue'
  
p1reader:
  - id: p1reader_esp
    uart_id: uart_bus
#  Size of the internal working buffer (default 60)
#    buffer_size: 3072
#    protocol: hdlc
#  OR (the default if left unset)
#    protocol: ascii

sensor:
  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_active_import:
      name: "Cumulative Active Import"

  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_active_export:
      name: "Cumulative Active Export"

  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_reactive_import:
      name: "Cumulative Reactive Import"

  - platform: p1reader
    p1reader_id: p1reader_esp
    cumulative_reactive_export:
      name: "Cumulative Reactive Export"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_import:
      name: "Momentary Active Import"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_export:
      name: "Momentary Active Export"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_import:
      name: "Momentary Reactive Import"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_export:
      name: "Momentary Reactive Export"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_import_l1:
      name: "Momentary Active Import Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_export_l1:
      name: "Momentary Active Export Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_import_l2:
      name: "Momentary Active Import Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_export_l2:
      name: "Momentary Active Export Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_import_l3:
      name: "Momentary Active Import Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_active_export_l3:
      name: "Momentary Active Export Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_import_l1:
      name: "Momentary Reactive Import Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_import_l2:
      name: "Momentary Reactive Import Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_import_l3:
      name: "Momentary Reactive Import Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_export_l1:
      name: "Momentary Reactive Export Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_export_l2:
      name: "Momentary Reactive Export Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    momentary_reactive_export_l3:
      name: "Momentary Reactive Export Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_esp
    voltage_l1:
      name: "Voltage Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    voltage_l2:
      name: "Voltage Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    voltage_l3:
      name: "Voltage Phase 3"

  - platform: p1reader
    p1reader_id: p1reader_esp
    current_l1:
      name: "Current Phase 1"

  - platform: p1reader
    p1reader_id: p1reader_esp
    current_l2:
      name: "Current Phase 2"

  - platform: p1reader
    p1reader_id: p1reader_esp
    current_l3:
      name: "Current Phase 3"
