# Bare minimum to ship HANP1 with!

substitutions:
  name: "hanp1"
  friendly_name: "HanP1, Electric meter for P1/HAN port"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  min_version: 2025.2.0
  project:
    name: HanP1.electrical meter
    version: "1.1.0"

esp8266:
  board: esp07s

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0 # disable logging over uart
  esp8266_store_log_strings_in_flash: false # Avoid flash wear and tear

# Enable Home Assistant API
api:

# OTA is required for Over-the-Air updating
ota:
  platform: esphome

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://Tozzi89/HanP1/hanp1.yaml@main
  import_full_config: False # or true

wifi:
  # Set up a wifi access point
  ap:
    password: "12345678"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

# Example configuration entry
web_server:
  port: 80

# Red LED
status_led:
  pin: 12

output:
  - platform: gpio
    pin: 13
    id: 'green'

  - platform: gpio
    pin: 14
    id: 'blue'

switch:
  - platform: output
    name: "Green"
    output: 'green'
    restore_mode: ALWAYS_ON

  - platform: output
    name: "Blue"
    output: 'blue'

    # Example configuration entry
button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
